import Head from "next/head";
import { ThemeProvider } from "@mui/system";
import { FC } from "react";

import theme from "../config/theme";

interface ILayoutProps {
	children: JSX.Element;
}

const Layout: FC<ILayoutProps> = ({ children }) => {
	return (
		<div>
			<Head>
				<title>Algrora 2.0</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ThemeProvider theme={theme}>{children}</ThemeProvider>
			{/* {children} */}
		</div>
	);
};

export default Layout;
